### ISSUE TITLE
Enrollment and Evaluation Dataset Problem

### ISSUE THREAD

**Issue by SameerGurjar** [astorfi/3D-convolutional-speaker-recognition#10]
how the shape is obtained in utterance_enrollment in enrollment-evaluation_sample_dataset.hdf5 : no_of_sample x 80 x 40 x1

**Comment by SameerGurjar** [comment]
D:\sp_rec\feaext\0-input\create_hdf5\development_sample_dataset_speaker.hdf5 (File) ''
Last modif.: 'Fri Oct 27 21:30:45 2017'
Object Tree:
/ (RootGroup) ''
/label_test (EArray(12,), shuffle, blosc(5)) ''
/label_train (EArray(12,), shuffle, blosc(5)) ''
/utterance_test (EArray(12, 80, 40, 20), shuffle, blosc(5)) ''
/utterance_train (EArray(12, 80, 40, 20), shuffle, blosc(5)) ''



D:\sp_rec\feaext\0-input\create_hdf5\enrollment-evaluation_sample_dataset.hdf5 (File) ''
Last modif.: 'Fri Mar 16 16:43:55 2018'
Object Tree:
/ (RootGroup) ''
/label_enrollment (EArray(108,), shuffle, blosc(5)) ''
/label_evaluation (EArray(12,), shuffle, blosc(5)) ''
/utterance_enrollment (EArray(108, 80, 40, 1), shuffle, blosc(5)) ''
/utterance_evaluation (EArray(12, 80, 40, 1), shuffle, blosc(5)) ''

**Comment by astorfi** [comment]
@SameerGurjar Please read the associated paper:
[Text-Independent Speaker Verification Using 3D Convolutional Neural Networks](https://arxiv.org/abs/1705.09422)
