### ISSUE TITLE
Data pipeline example

### ISSUE THREAD

**Issue by RefiPeretz** [astorfi/3D-convolutional-speaker-recognition#12]
I'm trying to figure out your pipeline including reading the paper with no luck so far. 
Clearly base on the open and and closed issues I'm not the only one. It seems a lot of work has been done here and quality work too. 
However this repository cries for a solid example from WAV file through feature extraction development enrollment and prediction. 
I know that each case need to customize it's pipeline by itself but in my point of view the example, paper and documentation doesn't give enough infrastructure to continue on your own.

Again it really seems I'm not the only one. Can you please upload a pipeline example , refer me to one or at least upload a clear description from WAV file to prediction.

**Comment by astorfi** [comment]
@RefiPeretz Thank you so much for your attention.
I am having plans to release an independent input pipeline for this repository. However, please consider some point:

1. This repository is not an independent project. It is technically the implementation of the following paper:
[Text-Independent Speaker Verification Using 3D Convolutional Neural Networks](https://arxiv.org/abs/1705.09422)

2. Please make sure that you understand the paper and after that following the threads in this repository will be straightforward.

3. Th main issue was the dataset that has been used in the paper is restricted and not a public one.

All in all, I understand your viewpoint and once again thank you for pointing it out. I am determined to improve the input pipeline section of the repository and your feedback is very valuable for me.
