### ISSUE TITLE
Mean and standard deviation comes NAN

### ISSUE THREAD

**Issue by maulikjethva** [astorfi/3D-convolutional-speaker-recognition#14]
Hi Astorfi,

Your paper is awesome.
I am trying to train speech data using 3D CNN.
I have prepared data according to mention in paper. but during development phase I am getting mean and standard deviation "nan" in each epoch. 
I am getting following output:

Epoch 1, Minibatch 1 of 3 , Minibatch Loss= 2.1972, TRAIN ACCURACY= 0.000
Epoch 1, Minibatch 2 of 3 , Minibatch Loss= 2.2215, TRAIN ACCURACY= 0.000
Epoch 1, Minibatch 3 of 3 , Minibatch Loss= 2.2637, TRAIN ACCURACY= 0.000
TESTING after finishing the training on: epoch 1
Test Accuracy 1, Mean= nan, std= nan

Can you please help me, why am I getting this problem?

**Comment by astorfi** [comment]
@maulikjethva Thank you for your kind words ... The mean and std are simply the mean and standard deviation of the accuracy per batch. Please make sure that the accuracy calculations are correct. Can you tell me what is the value of test_accuracy_vector?
