### ISSUE TITLE
shape mismatch problem in input_feature.py

### ISSUE THREAD

**Issue by yangalan123** [astorfi/3D-convolutional-speaker-recognition#17]
Hello! We are trying to make our own input pipeline. However, when we follow the __getitem__ method in Audioset (with the setting that cube_shape is (20,80,40)), there is a shape mismatch when the model tries to feed data for batch_speech (placeholder with the shape of (20,80,.40,1)). 

After carefully review the code in train_softmax.py, we find that the input shape will conflict with the transpose operation in following code:

 speech_train = np.transpose(speech_train[None, :, :, :, :], axes=(1, 4, 2, 3, 0))

What is the solution? Could you give us any help?

**Comment by astorfi** [comment]
Thank you for your question, the **getitem** is just for showcasing the deadline and all the shapes that you are mentioning are just my custom way of inputting data. The pipeline must by modify and adapted considering your desired architecture and etc. You can create the pipeline in a way that you don't even need **np.transpose** which makes the code slow for sure. Please go to the details of the provided class for input pipeline to grasp an idea about the details.

**Comment by yangalan123** [comment]
Sorry, but I didn't see a example class for input pipeline in the current commit(Do you mean input_feature.py?)  However, I do find make_development.py in the pase commit line. Could we just use it？ Are there some known bugs in make_development.py which makes you delete the file?

Thanks for your patience. Looking forward for your reply.

**Comment by astorfi** [comment]
If you are using an old fork please replace it with a new one. Yes, the [input_feature.py](https://github.com/astorfi/3D-convolutional-speaker-recognition/blob/master/code/0-input/input_feature.py) function is pretty much everything you need for the input pipeline.

**Comment by chenhaishun** [comment]
@yangalan123 hi~
I am also studying this project. I hope to have some exchanges with you.please~[QQ:540851498]

**Comment by yangalan123** [comment]
@chenhaishun Thank you for your kindness, but honestly I doesn't make detailed research about this field. I only want to make some application on the basis of this great paper. So...I am afraid I cannot help you much.

**Comment by yangalan123** [comment]
@astorfi Thank you for your kind help, I have found out a possible solution to incorporate input_feature.py into my project. I will close this issue in advance. If anyone has the similar questions, please reopen.

**Comment by chenhaishun** [comment]
Hi～
We can also communicate in other areas. To be honest in this area, I have only just started, and I still hope to share my experience with you.
So...please

**Comment by 0ifeng0** [comment]
@yangalan123 I have the same problem with the shape mismatch.Can you show your sulution?Thank you.
