### ISSUE TITLE
the feature of input data

### ISSUE THREAD

**Issue by chenhaishun** [astorfi/3D-convolutional-speaker-recognition#18]
Hi Astorfi,
First your work is prefect! I've read your paper and it's really great
In sample data of  your previous code， you are applying mfec feature file(feature_mfec.npy) contains shape (3209,40,3). As per my understanding 3209 is Number of Frames,40 is Number of Features,3(The 3 is the number of channels which consists of static, first order and second order derivative features.) Is number of Channels. (using speechpy.feature.extract_derivative_feature(feature))  right?
but in the input_feature.py function (you provided these days),the feature file output contains shape (1, 20, 80, 40),80 is Number of Frames,40 is Number of Features,20 is number of utterances,1 represents a cube of one speaker,right?
so in the input_feature.py just use the first channel of the MFEC features of the audio?
Thanks!

**Comment by astorfi** [comment]
Thank you for your kind words. "1" is actually the representation of the batch size which chosen to be as a sample from the data. "20" is the number of utterances and for the rest you are correct.

**Comment by chenhaishun** [comment]
Thank you very much for your reply!
In practice, overfitting occurs when training the network. The training data is a data set of 50 different speakers. In your paper, you mentioned that you used different 511 different speakers, right?
For the training set, how many different speakers can make the trained network have a better generalization？
Thanks!

**Comment by astorfi** [comment]
Generally, there is no magic number for that. Loosely speaking, the more is the better.
