### ISSUE TITLE
Error importing Tables

### ISSUE THREAD

**Issue by GValens** [astorfi/3D-convolutional-speaker-recognition#20]
Hello, first of all thank you for releasing the code. Unfortunately, I'm stuck at step 1 (step 0 works.)
I installed all the requirements, this is my setup:
Win7 64
Python 3.5.4
Tensorflow 1.6 (installed in a separate Anaconda environment but still wit pip install)
Tables 3.4.3
I also installed pytables from conda, I thought it was missing, but the result is still the same:

When running train_softmax, at 'import tables', I get: 
  File "C:\Users\...\AppData\Local\Continuum\Anaconda3\envs\tensorflow\lib\site-packages\tables\__init__.py", line 90, in <module>
    from .utilsextension import (

ImportError: DLL load failed: The specified procedure could not be found.

The thing is, if i simpy import tables with no code preceding it, it's fine. If I import it after tensorflow (as in your code), it gives me the error. If I move 'import tables' before 'import tensorflow', then python crashes.

I tried to find answers on the net but none was useful...

Thanks

**Comment by astorfi** [comment]
@GValens Please open this issue if the problem still remains. Thanks
