### ISSUE TITLE
FileNotFoundError: [Errno 2] No such file or directory: 'results/SCORES\\score_vector.npy'

### ISSUE THREAD

**Issue by boulbaba** [astorfi/3D-convolutional-speaker-recognition#21]
Hi Astorfi,
Your work is prefect! I've read your paper and it's actually great.
So im new in the field of tensorflow and all and im trying to learn.
Im having a problem when executing ./run.sh and this is the text error : 

Traceback (most recent call last):
  File "./code/4-ROC_PR_curve/PlotHIST.py", line 53, in <module>
    score = np.load(os.path.join(FLAGS.evaluation_dir,'score_vector.npy'))
  File "C:\Users\Boulbaba Zitouni\AppData\Local\Programs\Python\Python36\lib\site-packages\numpy\lib\npyio.py", line 372, in load
    fid = open(file, "rb")
FileNotFoundError: [Errno 2] No such file or directory: 'results/SCORES\\score_vector.npy'

i just cloned the project and tried to run it thats it 
i have already installed all the requierements (on the requierements.txt )

Any solutions ?

**Comment by astorfi** [comment]
Please have some few points in mind:

1- Please fork the latest update.
2- Make sure the evaluation code generates the correct evaluation scores in score_vector.npy.

**Comment by stuartcodepro** [comment]
Evening Astorfi,
I am getting the same error, and forked from your latest update. How do I ensure the correct code is generated in the score_vector.npy?

**Comment by astorfi** [comment]
@stuartcodepro Please follow the code step by step and make sure the results folder is generated. Furthermore, try to check the local folders and paths in the code regarding your environmental setup.

**Comment by imranparuk** [comment]
I get this error, but I suspect it is caused by another error...

``
ValueError: Convolution expects input with rank 4, got 5
``
This is caused by:

`` 
File "./code/1-development/train_softmax.py", line 416, in main
logits, end_points_speech = model_speech_fn(batch_speech[i * step: (i + 1) * step])
``
