### ISSUE TITLE
inputting dataset to development

### ISSUE THREAD

**Issue by lucasalin** [astorfi/3D-convolutional-speaker-recognition#22]
Hi astorfi,

I'm trying to train my own data set on your model. Is there also an update for the development files to feed dataset from input_features.py? It looks like train_softmax.py still takes in an hdf5 file.

Thanks,
Lucas

**Comment by astorfi** [comment]
Yes, please ignore that and feed your specific input customized for your dataset. HDF5 is not required. You only need to feed the data using feed_dict.
