### ISSUE TITLE
Speaker recognition possible

### ISSUE THREAD

**Issue by suresh-s** [astorfi/3D-convolutional-speaker-recognition#28]
Is Speaker recognition possible with this framework? I want to store the input voice pattern as part of enrolment process. then want to verify the input voice and find out who is currently speaking.

Is it possible?

**Comment by astorfi** [comment]
It is possible. You should utilize it as the one-vs-all scenario.
Please read the associated [paper](https://arxiv.org/abs/1705.09422) for further details.
