### ISSUE TITLE
EER vs i-vector

### ISSUE THREAD

**Issue by SpongebBob** [astorfi/3D-convolutional-speaker-recognition#33]
Hi astorfi,
Thanks for such a great work. The pipeline is really great.
 But I try ai-shell dataset the kaldi i-vector is around 2% eer.  3D-convolutional-speaker-recognitionwith LDA is 17% eer.
What's wrong? Any help will thank a lot!

**Comment by astorfi** [comment]
You mentioned,  "3D-convolutional-speaker-recognition with LDA".  Everything else is exactly the same? What is the dataset? What is the input length?

**Comment by astorfi** [comment]
@SpongebBob Consider that our model is a novel architecture based on 3D CNNs. It is not necessarily better than the other methods. For further improvement, I suggest to train and end to end method.

**Comment by SpongebBob** [comment]
@astorfi Thanks for your replay.  I use all the same settings in your code and paper. Without LDA, I get a 20.3% EER. And LDA give me 3% EER boosting. There is two much gap between i-vector.  I use the data and script in official kaldi examples: https://github.com/kaldi-asr/kaldi/tree/master/egs/aishell.

**Comment by astorfi** [comment]
@SpongebBob  I am not aware of Kaldi implementation. It's hard for me to tell the reason.
