### ISSUE TITLE
validate accuracy on development dataset

### ISSUE THREAD

**Issue by deyituo** [astorfi/3D-convolutional-speaker-recognition#34]
Hi astorfi,
Thanks for your great job. These days I am running your code on my dataset but I found it the validate accuracy is low in my experiments. I have no idea if there is something wrong. What's the validate accuracy of your experiments when the network is converged?

**Comment by SpongebBob** [comment]
I have the same question。Can you leave me a wechat or QQ？ Any help will thank a lot。
