### ISSUE TITLE
RuntimeWarning: numpy.dtype size changed

### ISSUE THREAD

**Issue by pranoot** [astorfi/3D-convolutional-speaker-recognition#37]
Hello,
Thank you for a wonderful work in speaker verification
I am trying to execute the code and its giving me the following error.
RuntimeWarning: numpy.dtype size changed, may indicate binary incompatibility. Expected 96, got 88

Is it because of the different versioning of numpy and scipy? If yes then what are the version which you have used while training?

Thank you for your help !

**Comment by astorfi** [comment]
@pranoot It's a warning. It is not an error. You can simply force the file types to be of the desired format but it is not a big deal.

**Comment by pranoot** [comment]
Thank you.
