### ISSUE TITLE
Where does input_feature.py store it's results?

### ISSUE THREAD

**Issue by Chegde8** [astorfi/3D-convolutional-speaker-recognition#44]
Hi,

I think train_softmax.py, enrollment.py and evaluation.py get their inputs from the hdf5 files stored in the data folder.
I also think that input_feature.py is supposed to store it's results in these hdf5 files.
But I am not able to figure out which part of the input_feature.py code is responsible for writing the results into the hdf5 files. 
Can someone please help me out with this?

Thanks

**Comment by astorfi** [comment]
It does not store results. It's for input data generation and following this code you can realize how the data is generated.
