### ISSUE TITLE
How to make Speaker Verification (1:1 recognition) model in keras?

### ISSUE THREAD

**Issue by ankitsuman80** [astorfi/3D-convolutional-speaker-recognition#45]
I have idea about the speaker identification model using CNN.

![image](https://user-images.githubusercontent.com/36723805/47545546-96efd300-d90a-11e8-8630-0f7f9e42a60e.png)

But here my question is how to make a verification model using the data that contains only positive value.
Suppose, i have voice data of my voice only and i want to create the verification model from this data such that when i run the model then it will only recognize me not anyone else.

please provide the code for it.

![image](https://user-images.githubusercontent.com/36723805/47545539-8d666b00-d90a-11e8-9cd3-6e39422a4534.png)

**Comment by astorfi** [comment]
Please read the paper associated to this repository for further information.
