### ISSUE TITLE
can't create enrollment hdf5 file

### ISSUE THREAD

**Issue by liveinnet** [astorfi/3D-convolutional-speaker-recognition#5]
Hi astorfi:
    i try to run the program but i can't find a python script to create enrollment hdf5 file
    in code folder only exist create development hdf5 python script.
    how to create enrollment hdf5 file? 

Mark

**Comment by astorfi** [comment]
@liveinnet Thanks for spending time. Creating development hdf5 is an example for showcasing how to do the task. Creating enrollment and etc can be similar to that and is dataset-based. Basically, the enrollment part is created similar to development phase with the difference of the identity of the speaker. The speaker subjects are disjoint in development and enrollment phases.
