### ISSUE TITLE
Do you mean "train_files_subjects_list.append(subject)" rather than "train_files_subjects_list.append(file_name.split('/')[7]"

### ISSUE THREAD

**Issue by duoduoliu0622** [astorfi/3D-convolutional-speaker-recognition#8]
https://github.com/astorfi/3D-convolutional-speaker-recognition/blob/61969eb2dba6004bdecb4f7100047015ca665348/code/0-input/create_hdf5/create_development.py#L132

**Comment by astorfi** [comment]
@duoduoliu0622 Yes, basically considering the naming convention of the dataset that I used, file_name.split('/')[7] gives the subject!
